"""Seed dataset for the 18 MVP source rows."""

from __future__ import annotations


def _rss_config(
    *,
    source_key: str,
    feed_url: str,
    fallback_feed_url: str | None = None,
    supports_etag: bool = False,
    supports_last_modified: bool = False,
    has_last_build_date: bool = False,
    ttl: int | None = None,
    use_guid_as_url: bool = False,
    url_source_field: str = "link",
    stop_early_on_known: bool = True,
    fetch_full_text: bool = False,
    full_text_method: str = "html_trafilatura",
    full_text_tag: str | None = None,
    fallback_full_text_tag: str | None = None,
    postprocess_rules: list[dict] | None = None,
    has_author: bool = False,
    author_format: str = "absent",
    has_category: bool = False,
    has_enclosure: bool = False,
    mixed_regional_hosts: bool = False,
    extra: dict | None = None,
) -> dict:
    config = {
        "source_key": source_key,
        "feed_url": feed_url,
        "supports_etag": supports_etag,
        "supports_last_modified": supports_last_modified,
        "has_last_build_date": has_last_build_date,
        "use_guid_as_url": use_guid_as_url,
        "url_source_field": url_source_field,
        "stop_early_on_known": stop_early_on_known,
        "canonical_keep_params": [],
        "fetch_full_text": fetch_full_text,
        "full_text_method": full_text_method,
        "postprocess_rules": postprocess_rules or [],
        "has_author": has_author,
        "author_format": author_format,
        "has_category": has_category,
        "has_enclosure": has_enclosure,
        "mixed_regional_hosts": mixed_regional_hosts,
    }
    if fallback_feed_url:
        config["fallback_feed_url"] = fallback_feed_url
    if ttl is not None:
        config["ttl"] = ttl
    if full_text_tag:
        config["full_text_tag"] = full_text_tag
    if fallback_full_text_tag:
        config["fallback_full_text_tag"] = fallback_full_text_tag
    if extra:
        config.update(extra)
    return config


SOURCE_SEED_DATA: list[dict] = [
    {
        "name": "ТАСС",
        "type": "rss",
        "url": "https://tass.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 15,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.85,
        "reliability": "A",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="tass",
            feed_url="https://tass.ru/rss/yandex.xml",
            fallback_feed_url="https://tass.ru/rss/v2.xml",
            url_source_field="pdalink",
            full_text_method="rss_yandex_fulltext",
            full_text_tag="yandex:full-text",
            has_category=True,
            has_enclosure=True,
        ),
    },
    {
        "name": "РИА Новости",
        "type": "rss",
        "url": "https://ria.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 15,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.80,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="ria",
            feed_url="https://ria.ru/export/rss2/archive/index.xml",
            full_text_method="html_source_specific",
            has_category=True,
            extra={
                "namespace_prefixes": ["rian"],
                "extraction_strategy": {
                    "body_selector": ".article__body",
                    "text_block_selector": ".article__block[data-type='text'] .article__text",
                },
            },
        ),
    },
    {
        "name": "РБК",
        "type": "rss",
        "url": "https://www.rbc.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.85,
        "reliability": "A",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="rbc",
            feed_url="https://rssexport.rbc.ru/rbcnews/news/30/full.rss",
            url_source_field="pdalink",
            full_text_method="rss_custom_namespace",
            full_text_tag="rbc_news:full-text",
            has_author=True,
            author_format="fio",
            has_category=True,
            has_enclosure=True,
            postprocess_rules=[
                {
                    "type": "regex_strip_tail",
                    "pattern": "\\s*Оставайтесь на связи с РБК.*$",
                    "flags": "s",
                },
                {"type": "html_unescape", "fields": ["snippet_lead"]},
            ],
            extra={"custom_namespace_prefix": "rbc_news"},
        ),
    },
    {
        "name": "Ведомости news",
        "type": "rss",
        "url": "https://www.vedomosti.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.90,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="vedomosti_news",
            feed_url="https://www.vedomosti.ru/rss/news",
            supports_etag=True,
            supports_last_modified=True,
            full_text_method="html_source_specific",
            has_author=True,
            author_format="channel_name",
            has_category=True,
            extra={
                "extraction_strategy": {
                    "body_selector": ".article-boxes-list",
                    "text_block_selector": ".article-boxes-list__item .box-paragraph__text",
                }
            },
        ),
    },
    {
        "name": "Ведомости articles",
        "type": "rss",
        "url": "https://www.vedomosti.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.92,
        "reliability": "B",
        "default_info_type": "analytics",
        "default_content_type": "analysis",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="vedomosti_articles",
            feed_url="https://www.vedomosti.ru/rss/articles",
            supports_etag=True,
            supports_last_modified=True,
            full_text_method="html_source_specific",
            has_author=True,
            author_format="channel_name",
            has_category=True,
            extra={
                "extraction_strategy": {
                    "body_selector": ".article-boxes-list",
                    "text_block_selector": ".article-boxes-list__item .box-paragraph__text",
                }
            },
        ),
    },
    {
        "name": "Коммерсантъ news",
        "type": "rss",
        "url": "https://www.kommersant.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.85,
        "reliability": "A",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "public_rss",
        "config": _rss_config(
            source_key="kommersant_news",
            feed_url="https://www.kommersant.ru/rss/news.xml",
            supports_etag=True,
            supports_last_modified=True,
            full_text_method="html_trafilatura",
            has_category=True,
            has_enclosure=True,
            postprocess_rules=[
                {
                    "type": "remove_lines_starting_with",
                    "prefixes": ["\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435", "\u0424\u043e\u0442\u043e:"],
                },
                {
                    "type": "regex_strip_tail",
                    "pattern": "\\s*\\u041d\\u043e\\u0432\\u043e\\u0441\\u0442\\u0438 \\u043a\\u043e\\u043c\\u043f\\u0430\\u043d\\u0438\\u0439\\s*$",
                },
            ],
        ),
    },
    {
        "name": "Коммерсантъ corp",
        "type": "rss",
        "url": "https://www.kommersant.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 60,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.85,
        "reliability": "A",
        "default_info_type": "analytics",
        "default_content_type": "analysis",
        "is_active": True,
        "legal_status": "public_rss",
        "config": _rss_config(
            source_key="kommersant_corp",
            feed_url="https://www.kommersant.ru/rss/corp.xml",
            supports_etag=True,
            supports_last_modified=True,
            full_text_method="html_trafilatura",
            has_category=True,
            has_enclosure=True,
            postprocess_rules=[
                {
                    "type": "remove_lines_starting_with",
                    "prefixes": ["\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435", "\u0424\u043e\u0442\u043e:"],
                },
                {
                    "type": "regex_strip_tail",
                    "pattern": "\\s*\\u041d\\u043e\\u0432\\u043e\\u0441\\u0442\\u0438 \\u043a\\u043e\\u043c\\u043f\\u0430\\u043d\\u0438\\u0439\\s*$",
                },
            ],
            extra={"split_title_on": " // "},
        ),
    },
    {
        "name": "Коммерсантъ main",
        "type": "rss",
        "url": "https://www.kommersant.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 120,
        "crawl_delay": 1.0,
        "priority": "control",
        "trust_score": 0.90,
        "reliability": "A",
        "default_info_type": "analytics",
        "default_content_type": "analysis",
        "legal_status": "public_rss",
        "config": _rss_config(
            source_key="kommersant_main",
            feed_url="https://www.kommersant.ru/rss/main.xml",
            supports_etag=True,
            supports_last_modified=True,
            full_text_method="html_trafilatura",
            has_category=True,
            has_enclosure=True,
            postprocess_rules=[
                {
                    "type": "remove_lines_starting_with",
                    "prefixes": ["\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435", "\u0424\u043e\u0442\u043e:"],
                },
                {
                    "type": "regex_strip_tail",
                    "pattern": "\\s*\\u041d\\u043e\\u0432\\u043e\\u0441\\u0442\\u0438 \\u043a\\u043e\\u043c\\u043f\\u0430\\u043d\\u0438\\u0439\\s*$",
                },
            ],
            extra={"split_title_on": " // "},
        ),
    },
    {
        "name": "Lenta.ru",
        "type": "rss",
        "url": "https://lenta.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.72,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "public_rss",
        "config": _rss_config(
            source_key="lenta",
            feed_url="https://lenta.ru/rss",
            supports_etag=True,
            full_text_method="html_trafilatura",
            has_author=True,
            author_format="fio",
            has_category=True,
            has_enclosure=True,
        ),
    },
    {
        "name": "МК",
        "type": "rss",
        "url": "https://www.mk.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 15,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.78,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="mk",
            feed_url="https://www.mk.ru/rss/index.xml",
            has_last_build_date=True,
            full_text_method="html_trafilatura",
            has_category=True,
            has_enclosure=True,
            mixed_regional_hosts=True,
            postprocess_rules=[
                {
                    "type": "regex_strip_tail",
                    "pattern": r"\s*Ваша надежная лента новостей\s*—\s*МК в MAX\.?\s*$",
                    "flags": "s",
                },
            ],
        ),
    },
    {
        "name": "Life.ru",
        "type": "rss",
        "url": "https://life.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.55,
        "reliability": "C",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "public_rss",
        "config": _rss_config(
            source_key="life",
            feed_url="https://life.ru/rss",
            supports_etag=True,
            full_text_method="html_trafilatura",
            has_category=True,
            has_enclosure=True,
        ),
    },
    {
        "name": "CNews",
        "type": "rss",
        "url": "https://www.cnews.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.80,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="cnews",
            feed_url="https://www.cnews.ru/inc/rss/news.xml",
            supports_etag=True,
            supports_last_modified=True,
            full_text_method="html_trafilatura",
            has_category=True,
            has_enclosure=True,
            extra={
                "fallback_feed_urls": [
                    "https://windows8.cnews.ru/inc/rss/news.xml",
                    "https://telecomb2b.cnews.ru/inc/rss/news.xml",
                ]
            },
        ),
    },
    {
        "name": "BFM.ru",
        "type": "rss",
        "url": "https://www.bfm.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.82,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "public_rss",
        "config": _rss_config(
            source_key="bfm",
            feed_url="https://www.bfm.ru/news.rss?type=news",
            full_text_method="html_source_specific",
            has_author=True,
            author_format="fio",
            postprocess_rules=[
                {"type": "remove_lines_starting_with", "prefixes": ["Лента новостей", "Все новости"]},
            ],
        ),
    },
    {
        "name": "iXBT.com",
        "type": "rss",
        "url": "https://www.ixbt.com",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.80,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "public_rss",
        "config": _rss_config(
            source_key="ixbt",
            feed_url="https://www.ixbt.com/export/news.rss",
            full_text_method="rss_description_html",
            full_text_tag="encoded",
            has_author=True,
            author_format="email_pseudonym",
            has_enclosure=True,
            postprocess_rules=[
                {"type": "bs4_decompose_selector", "selector": "a[href*='utm_campaign=seealso']"},
                {"type": "bs4_decompose_selector", "selector": "a:has(figure)"},
                {"type": "bs4_decompose_selector", "selector": "figure"},
                {"type": "remove_lines_starting_with", "prefixes": ["Фото", "Создано", "Photo"]},
            ],
        ),
    },
    {
        "name": "Хабр",
        "type": "rss",
        "url": "https://habr.com/ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 120,
        "crawl_delay": 10.0,
        "priority": "control",
        "trust_score": 0.80,
        "reliability": "B",
        "default_info_type": "analytics",
        "default_content_type": "analysis",
        "legal_status": "public_rss",
        "config": _rss_config(
            source_key="habr",
            feed_url="https://habr.com/ru/rss/articles/?fl=ru&limit=100&with_hubs=true",
            use_guid_as_url=True,
            full_text_method="html_trafilatura",
            has_author=True,
            author_format="username",
            has_category=True,
        ),
    },
    {
        "name": "RT на русском",
        "type": "rss",
        "url": "https://russian.rt.com",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.70,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="rt",
            feed_url="https://russian.rt.com/rss",
            full_text_method="html_source_specific",
            has_author=True,
            author_format="channel_name",
            has_category=True,
            postprocess_rules=[
                {
                    "type": "regex_strip_tail",
                    "pattern": "\\s*Читать далее\\.?\\s*$",
                    "fields": ["snippet_lead"],
                },
            ],
            extra={
                "section_from_url": True,
                "extraction_strategy": {
                    "css_blocks": [".article__summary", ".article__text"],
                    "tags_block": ".article__tags-trends",
                },
            },
        ),
    },
    {
        "name": "АиФ news",
        "type": "rss",
        "url": "https://aif.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 30,
        "crawl_delay": 1.0,
        "priority": "periodic",
        "trust_score": 0.82,
        "reliability": "B",
        "default_info_type": "daily",
        "default_content_type": "news",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="aif_news",
            feed_url="https://aif.ru/rss/news.php",
            has_last_build_date=True,
            full_text_method="rss_turbo_structured",
            full_text_tag="turbo:content",
            fallback_full_text_tag="yandex:full-text",
            has_author=True,
            author_format="fio",
            has_category=True,
            has_enclosure=True,
            postprocess_rules=[
                {"type": "bs4_decompose_selector", "selector": "header"},
                {"type": "bs4_decompose_selector", "selector": "ExtRetellWidget"},
                {"type": "bs4_decompose_selector", "selector": "Ext24smiWidget"},
                {"type": "bs4_decompose_selector", "selector": "ExtSvkNativeWidget"},
                {"type": "bs4_decompose_figures_with_data_attr", "data_attr": "data-turbo-ad-id"},
            ],
            extra={"read_theme_tags": True, "read_related_links": True},
        ),
    },
    {
        "name": "АиФ articles",
        "type": "rss",
        "url": "https://aif.ru",
        "engine": "httpx",
        "delivery_mode": "pull",
        "crawl_interval": 60,
        "crawl_delay": 1.0,
        "priority": "control",
        "trust_score": 0.82,
        "reliability": "B",
        "default_info_type": "analytics",
        "default_content_type": "analysis",
        "legal_status": "restricted",
        "config": _rss_config(
            source_key="aif_articles",
            feed_url="https://aif.ru/rss/articles.php",
            has_last_build_date=True,
            full_text_method="rss_turbo_structured",
            full_text_tag="turbo:content",
            fallback_full_text_tag="yandex:full-text",
            has_author=True,
            author_format="fio",
            has_category=True,
            has_enclosure=True,
            postprocess_rules=[
                {"type": "bs4_decompose_selector", "selector": "header"},
                {"type": "bs4_decompose_selector", "selector": "ExtRetellWidget"},
                {"type": "bs4_decompose_selector", "selector": "Ext24smiWidget"},
                {"type": "bs4_decompose_selector", "selector": "ExtSvkNativeWidget"},
                {"type": "bs4_decompose_figures_with_data_attr", "data_attr": "data-turbo-ad-id"},
            ],
            extra={"read_theme_tags": True, "read_related_links": True},
        ),
    },
]
