/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Feed */
        get: operations["get_news_feed_api_v1_news_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Sources */
        get: operations["get_news_sources_api_v1_news_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News Topics */
        get: operations["get_news_topics_api_v1_news_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news_api_v1_news__news_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{news_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Related News */
        get: operations["get_related_news_api_v1_news__news_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Run objective Layer 3 search and Layer 4 personalization/diversity.
         */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest */
        get: operations["suggest_api_v1_search_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Logs */
        get: operations["search_logs_api_v1_search_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_api_v1_chat_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Digest */
        get: operations["get_digest_api_v1_digest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digest/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Digest */
        post: operations["generate_digest_api_v1_digest_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Digests */
        get: operations["list_digests_api_v1_digests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digest/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Digest Audio */
        get: operations["digest_audio_api_v1_digest_audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Preferences */
        put: operations["update_preferences_api_v1_profile_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interactions */
        get: operations["interactions_api_v1_profile_interactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trending Entities */
        get: operations["trending_entities_api_v1_entities_trending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Detail */
        get: operations["entity_detail_api_v1_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe Entity */
        post: operations["subscribe_entity_api_v1_entities__entity_id__subscribe_post"];
        /** Unsubscribe Entity */
        delete: operations["unsubscribe_entity_api_v1_entities__entity_id__subscribe_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_v1_admin_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/processing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Processing */
        get: operations["processing_api_v1_admin_processing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/search-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Stats */
        get: operations["search_stats_api_v1_admin_search_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/generation-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generation Stats */
        get: operations["generation_stats_api_v1_admin_generation_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminGenerationStatsResponse */
        AdminGenerationStatsResponse: {
            /** Total Generations */
            total_generations: number;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
            /** Rag Modes */
            rag_modes: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: {
                [key: string]: number;
            };
            /** Recent Generations */
            recent_generations: Record<string, never>[];
        };
        /** AdminOverviewResponse */
        AdminOverviewResponse: {
            /** Corpus */
            corpus: {
                [key: string]: number;
            };
            /** Infrastructure */
            infrastructure: {
                [key: string]: string;
            };
            /** Recent Errors */
            recent_errors?: Record<string, never>[];
        };
        /** AdminProcessingResponse */
        AdminProcessingResponse: {
            /** Processed */
            processed: number;
            /** Unprocessed */
            unprocessed: number;
            /** Chunks */
            chunks: number;
            /** Qdrant */
            qdrant: Record<string, never>;
        };
        /** AdminSearchStatsResponse */
        AdminSearchStatsResponse: {
            /** Total Searches */
            total_searches: number;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
            /** Cache Hit Count */
            cache_hit_count: number;
            /** Retrieval Modes */
            retrieval_modes: {
                [key: string]: number;
            };
            /** Recent Queries */
            recent_queries: Record<string, never>[];
        };
        /** AdminSourceItem */
        AdminSourceItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Is Active */
            is_active: boolean;
            /** Health Status */
            health_status: string;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Parse Success Rate */
            parse_success_rate?: number | null;
            /** Extraction Success Rate */
            extraction_success_rate?: number | null;
            /** Last Crawled */
            last_crawled?: string | null;
            /** Last Error */
            last_error?: string | null;
        };
        /** AdminSourcesResponse */
        AdminSourcesResponse: {
            /** Items */
            items: components["schemas"]["AdminSourceItem"][];
        };
        /** ChatMessageItem */
        ChatMessageItem: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Generation Log Id */
            generation_log_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatMessagesResponse */
        ChatMessagesResponse: {
            /** Session Id */
            session_id: number;
            /** Messages */
            messages: components["schemas"]["ChatMessageItem"][];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id?: number | null;
            /**
             * Mode
             * @default standard
             */
            mode: string;
            /**
             * Limit
             * @default 8
             */
            limit: number;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Session Id */
            session_id?: number | null;
            /** Answer */
            answer: string;
            /** Confidence */
            confidence: string;
            /** Rag Mode */
            rag_mode: string;
            /** Model Name */
            model_name: string;
            /** Generation Log Id */
            generation_log_id?: number | null;
            /** Search Time Ms */
            search_time_ms?: number | null;
            /** Sources */
            sources: components["schemas"]["ChatSource"][];
            /**
             * Citation Valid
             * @default true
             */
            citation_valid: boolean;
            /**
             * Groundedness Score
             * @default 1
             */
            groundedness_score: number;
            /**
             * Has Unsupported Claims
             * @default false
             */
            has_unsupported_claims: boolean;
        };
        /** ChatSessionItem */
        ChatSessionItem: {
            /** Id */
            id: number;
            /** Title */
            title?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Message At */
            last_message_at?: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** ChatSessionsResponse */
        ChatSessionsResponse: {
            /** Items */
            items: components["schemas"]["ChatSessionItem"][];
        };
        /** ChatSource */
        ChatSource: {
            /** News Id */
            news_id: number;
            /** Source Name */
            source_name: string;
            /** Title */
            title: string;
            /**
             * Url
             * @default
             */
            url: string;
        };
        /** DigestAudioStatusResponse */
        DigestAudioStatusResponse: {
            /** Status */
            status: string;
            /** Detail */
            detail?: Record<string, never>;
        };
        /** DigestGenerateRequest */
        DigestGenerateRequest: {
            /**
             * Digest Type
             * @default on_demand
             */
            digest_type: string;
            /**
             * Query
             * @default главные новости сегодня
             */
            query: string;
            /**
             * Limit
             * @default 40
             */
            limit: number;
            /** Digest Style */
            digest_style?: string | null;
            /** Topics */
            topics?: string[];
            /** Period Hours */
            period_hours?: number | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** DigestItemView */
        DigestItemView: {
            /** News Id */
            news_id: number;
            /** Position */
            position: number;
            /** Snippet */
            snippet?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** DigestListResponse */
        DigestListResponse: {
            /** Items */
            items: components["schemas"]["DigestResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** DigestResponse */
        DigestResponse: {
            /** Id */
            id: number;
            /** Digest Type */
            digest_type: string;
            /** Content Text */
            content_text: string;
            /** News Count */
            news_count: number;
            /** Topics Covered */
            topics_covered?: string[];
            /** Generation Log Id */
            generation_log_id?: number | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Audio Path */
            audio_path?: string | null;
            /** Items */
            items?: components["schemas"]["DigestItemView"][];
        };
        /** EntityDetailResponse */
        EntityDetailResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Normalized Name */
            normalized_name?: string | null;
            /** Mention Count */
            mention_count: number;
            profile: components["schemas"]["EntityProfileView"];
            /** Recent News */
            recent_news?: components["schemas"]["NewsSummary"][];
        };
        /**
         * EntityPreferenceInput
         * @description User-configurable entity weight.
         */
        EntityPreferenceInput: {
            /** Entity Id */
            entity_id: number;
            /** Weight */
            weight: number;
        };
        /**
         * EntityPreferenceView
         * @description Entity weight plus entity name.
         */
        EntityPreferenceView: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name?: string | null;
            /** Weight */
            weight: number;
        };
        /** EntityProfileView */
        EntityProfileView: {
            /** Mention Freq Baseline */
            mention_freq_baseline?: number | null;
            /** Mention Freq Current */
            mention_freq_current?: number | null;
            /**
             * Source Diversity
             * @default 0
             */
            source_diversity: number;
            /**
             * Trend Direction
             * @default stable
             */
            trend_direction: string;
            /** Last Updated */
            last_updated?: string | null;
        };
        /** EntitySubscribeRequest */
        EntitySubscribeRequest: {
            /**
             * Alert On Spike
             * @default true
             */
            alert_on_spike: boolean;
            /**
             * Alert On News
             * @default true
             */
            alert_on_news: boolean;
        };
        /** EntitySubscribeResponse */
        EntitySubscribeResponse: {
            /** Entity Id */
            entity_id: number;
            /** Alert On Spike */
            alert_on_spike: boolean;
            /** Alert On News */
            alert_on_news: boolean;
        };
        /**
         * EntitySubscriptionInput
         * @description Explicit entity subscription settings.
         */
        EntitySubscriptionInput: {
            /** Entity Id */
            entity_id: number;
            /**
             * Alert On Spike
             * @default true
             */
            alert_on_spike: boolean;
            /**
             * Alert On News
             * @default true
             */
            alert_on_news: boolean;
        };
        /**
         * EntitySubscriptionView
         * @description Entity subscription plus entity name.
         */
        EntitySubscriptionView: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name?: string | null;
            /** Alert On Spike */
            alert_on_spike: boolean;
            /** Alert On News */
            alert_on_news: boolean;
        };
        /** EntityView */
        EntityView: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Normalized Name */
            normalized_name?: string | null;
            /** Mention Count */
            mention_count?: number | null;
        };
        /**
         * ExplicitPreferencesResponse
         * @description Complete explicit-preferences snapshot for one user.
         */
        ExplicitPreferencesResponse: {
            profile: components["schemas"]["UserProfileView"];
            /** Topic Weights */
            topic_weights?: components["schemas"]["TopicPreferenceView"][];
            /** Entity Weights */
            entity_weights?: components["schemas"]["EntityPreferenceView"][];
            /** Entity Subscriptions */
            entity_subscriptions?: components["schemas"]["EntitySubscriptionView"][];
            /** Tracked Keywords */
            tracked_keywords?: components["schemas"]["TrackedKeywordView"][];
            /** Source Preferences */
            source_preferences?: components["schemas"]["SourcePreferenceView"][];
        };
        /**
         * ExplicitPreferencesUpdateRequest
         * @description Full explicit-preferences update payload for one user.
         */
        ExplicitPreferencesUpdateRequest: {
            profile: components["schemas"]["UserProfilePatch"];
            /** Topic Weights */
            topic_weights?: components["schemas"]["TopicPreferenceInput"][];
            /** Entity Weights */
            entity_weights?: components["schemas"]["EntityPreferenceInput"][];
            /** Entity Subscriptions */
            entity_subscriptions?: components["schemas"]["EntitySubscriptionInput"][];
            /** Tracked Keywords */
            tracked_keywords?: components["schemas"]["TrackedKeywordInput"][];
            /** Source Preferences */
            source_preferences?: components["schemas"]["SourcePreferenceInput"][];
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** News Id */
            news_id: number;
            /** Action */
            action: string;
            /** Dwell Time Sec */
            dwell_time_sec?: number | null;
            /** Search Log Id */
            search_log_id?: number | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Recorded */
            recorded: boolean;
            /** Interaction Id */
            interaction_id: number;
            /** Stored Action */
            stored_action: string;
            /** Derived Signal */
            derived_signal: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** InteractionItem */
        InteractionItem: {
            /** Id */
            id: number;
            /** News Id */
            news_id: number;
            /** Title */
            title?: string | null;
            /** Action */
            action: string;
            /** Dwell Time Sec */
            dwell_time_sec?: number | null;
            /** Search Log Id */
            search_log_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InteractionsResponse */
        InteractionsResponse: {
            /** Items */
            items: components["schemas"]["InteractionItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** NewsDetail */
        NewsDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Snippet */
            snippet?: string | null;
            source: components["schemas"]["SourceBrief"];
            /** Url */
            url: string;
            /** Published At */
            published_at?: string | null;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Content Grade */
            content_grade: number;
            /** Information Type */
            information_type: string;
            /** Urgency */
            urgency: string;
            /** Is Uncertain */
            is_uncertain: boolean;
            /** Processed */
            processed: boolean;
            /** Topics */
            topics?: components["schemas"]["TopicView"][];
            /** Entities */
            entities?: components["schemas"]["EntityView"][];
            /** Content */
            content?: string | null;
            /** Canonical Url */
            canonical_url: string;
            /** Language */
            language: string;
            /** Content Status */
            content_status: string;
            /** Extraction Method */
            extraction_method?: string | null;
            /** Event Cluster Id */
            event_cluster_id?: number | null;
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /** Extra */
            extra?: Record<string, never>;
        };
        /** NewsFeedResponse */
        NewsFeedResponse: {
            /** Items */
            items: components["schemas"]["NewsSummary"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** NewsSourceFilterItem */
        NewsSourceFilterItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Url */
            url?: string | null;
            /** Health Status */
            health_status?: string | null;
            /** Trust Score */
            trust_score?: number | null;
            /**
             * News Count
             * @default 0
             */
            news_count: number;
            /**
             * Processed Count
             * @default 0
             */
            processed_count: number;
        };
        /** NewsSourceFiltersResponse */
        NewsSourceFiltersResponse: {
            /** Items */
            items: components["schemas"]["NewsSourceFilterItem"][];
        };
        /** NewsSummary */
        NewsSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Snippet */
            snippet?: string | null;
            source: components["schemas"]["SourceBrief"];
            /** Url */
            url: string;
            /** Published At */
            published_at?: string | null;
            /**
             * Ingested At
             * Format: date-time
             */
            ingested_at: string;
            /** Content Grade */
            content_grade: number;
            /** Information Type */
            information_type: string;
            /** Urgency */
            urgency: string;
            /** Is Uncertain */
            is_uncertain: boolean;
            /** Processed */
            processed: boolean;
            /** Topics */
            topics?: components["schemas"]["TopicView"][];
            /** Entities */
            entities?: components["schemas"]["EntityView"][];
        };
        /** NewsTopicFilterItem */
        NewsTopicFilterItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * News Count
             * @default 0
             */
            news_count: number;
        };
        /** NewsTopicFiltersResponse */
        NewsTopicFiltersResponse: {
            /** Items */
            items: components["schemas"]["NewsTopicFilterItem"][];
        };
        /** PageMeta */
        PageMeta: {
            /** Limit */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Total */
            total: number;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Status */
            status: string;
            /** Checks */
            checks: {
                [key: string]: string;
            };
        };
        /** RelatedNewsResponse */
        RelatedNewsResponse: {
            /** Items */
            items: components["schemas"]["NewsSummary"][];
        };
        /** SearchApiRequest */
        SearchApiRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            filters?: components["schemas"]["SearchFilters"] | null;
        };
        /** SearchApiResponse */
        SearchApiResponse: {
            /** Query */
            query: string;
            /** Corrected Query */
            corrected_query?: string | null;
            /** Intent */
            intent: string;
            /** Total */
            total: number;
            /** Search Time Ms */
            search_time_ms: number;
            /** Results */
            results: components["schemas"]["SearchApiResult"][];
        };
        /** SearchApiResult */
        SearchApiResult: {
            /** News Id */
            news_id: number;
            /** Source Id */
            source_id: number;
            /** Source Name */
            source_name: string;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /** Base Score */
            base_score: number;
            /** Personalized Score */
            personalized_score: number;
            /** Retrieval Mode */
            retrieval_mode?: string | null;
            /** Rerank Score */
            rerank_score?: number | null;
            /** Trust Score */
            trust_score: number;
            /** Content Grade */
            content_grade: number;
            /** Information Type */
            information_type: string;
            /** Urgency */
            urgency: string;
            /** Event Cluster Id */
            event_cluster_id?: number | null;
            /** Published At */
            published_at?: string | null;
            /** Topics */
            topics?: string[];
            /** Entities */
            entities?: string[];
            /** Explanation */
            explanation?: string | null;
            /** Personalization Reasons */
            personalization_reasons?: string[];
        };
        /**
         * SearchFilters
         * @description Optional filters for search.
         */
        SearchFilters: {
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Source Ids */
            source_ids?: number[] | null;
            /** Topics */
            topics?: string[] | null;
            /** Zone */
            zone?: string | null;
            /** Content Grade */
            content_grade?: number | null;
            /** Content Grade Max */
            content_grade_max?: number | null;
            /** Urgency */
            urgency?: string | null;
            /** Information Type */
            information_type?: string | null;
            /** Event Cluster Id */
            event_cluster_id?: number | null;
            /**
             * Language
             * @default ru
             */
            language: string;
        };
        /** SearchLogItem */
        SearchLogItem: {
            /** Id */
            id: number;
            /** Query Text */
            query_text: string;
            /** Resolved Query */
            resolved_query?: string | null;
            /** Intent */
            intent?: string | null;
            /** Num Results */
            num_results: number;
            /** Retrieval Time Ms */
            retrieval_time_ms: number;
            /** Cache Hit */
            cache_hit: boolean;
            /** Retrieval Mode */
            retrieval_mode: string;
            /** Top Result Ids */
            top_result_ids: number[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SearchLogsResponse */
        SearchLogsResponse: {
            /** Items */
            items: components["schemas"]["SearchLogItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** SearchSuggestionResponse */
        SearchSuggestionResponse: {
            /** Suggestions */
            suggestions: string[];
        };
        /** SourceBrief */
        SourceBrief: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Url */
            url?: string | null;
            /** Health Status */
            health_status?: string | null;
            /** Trust Score */
            trust_score?: number | null;
        };
        /**
         * SourcePreferenceInput
         * @description User relation to a source.
         */
        SourcePreferenceInput: {
            /** Source Id */
            source_id: number;
            /** Preference */
            preference: string;
        };
        /**
         * SourcePreferenceView
         * @description Source preference plus source name.
         */
        SourcePreferenceView: {
            /** Source Id */
            source_id: number;
            /** Name */
            name?: string | null;
            /** Preference */
            preference: string;
        };
        /**
         * TopicPreferenceInput
         * @description User-configurable topic weight.
         */
        TopicPreferenceInput: {
            /** Topic Id */
            topic_id: number;
            /** Weight */
            weight: number;
        };
        /**
         * TopicPreferenceView
         * @description Topic weight plus topic name.
         */
        TopicPreferenceView: {
            /** Topic Id */
            topic_id: number;
            /** Name */
            name?: string | null;
            /** Weight */
            weight: number;
        };
        /** TopicView */
        TopicView: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * TrackedKeywordInput
         * @description Arbitrary keyword tracked by the user.
         */
        TrackedKeywordInput: {
            /** Keyword */
            keyword: string;
        };
        /**
         * TrackedKeywordView
         * @description Tracked keyword value.
         */
        TrackedKeywordView: {
            /** Keyword */
            keyword: string;
        };
        /** TrendingEntitiesResponse */
        TrendingEntitiesResponse: {
            /** Items */
            items?: components["schemas"]["TrendingEntityItem"][];
        };
        /** TrendingEntityItem */
        TrendingEntityItem: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Normalized Name */
            normalized_name?: string | null;
            /** Mention Freq Baseline */
            mention_freq_baseline?: number | null;
            /** Mention Freq Current */
            mention_freq_current?: number | null;
            /**
             * Source Diversity
             * @default 0
             */
            source_diversity: number;
            /**
             * Trend Direction
             * @default stable
             */
            trend_direction: string;
            /** Last Updated */
            last_updated?: string | null;
        };
        /**
         * UserProfilePatch
         * @description Explicit user-facing profile fields.
         */
        UserProfilePatch: {
            /** User Id */
            user_id?: number | null;
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Telegram Id */
            telegram_id?: number | null;
            /** Settings */
            settings?: Record<string, never> | null;
        };
        /**
         * UserProfileView
         * @description Profile view returned by the service.
         */
        UserProfileView: {
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
            /** Telegram Id */
            telegram_id?: number | null;
            /** Settings */
            settings: Record<string, never>;
            /** Created At */
            created_at?: string | null;
            /** Last Active At */
            last_active_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    get_news_feed_api_v1_news_feed_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                source_id?: number | null;
                source_ids?: number[] | null;
                topic?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                content_grade_max?: number | null;
                processed_only?: boolean;
                personalized?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_sources_api_v1_news_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsSourceFiltersResponse"];
                };
            };
        };
    };
    get_news_topics_api_v1_news_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsTopicFiltersResponse"];
                };
            };
        };
    };
    get_news_api_v1_news__news_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                news_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_related_news_api_v1_news__news_id__related_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                news_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedNewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchApiRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_v1_search_suggest_get: {
        parameters: {
            query?: {
                query?: string | null;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_logs_api_v1_search_logs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchLogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_api_v1_chat_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_digest_api_v1_digest_get: {
        parameters: {
            query?: {
                digest_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_digest_api_v1_digest_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DigestGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_digests_api_v1_digests_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    digest_audio_api_v1_digest_audio_get: {
        parameters: {
            query: {
                digest_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Digest audio file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": unknown;
                };
            };
            /** @description Audio generation has not completed yet */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestAudioStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplicitPreferencesResponse"];
                };
            };
        };
    };
    update_preferences_api_v1_profile_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplicitPreferencesUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplicitPreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interactions_api_v1_profile_interactions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trending_entities_api_v1_entities_trending_get: {
        parameters: {
            query?: {
                limit?: number;
                period_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendingEntitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_detail_api_v1_entities__entity_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscribe_entity_api_v1_entities__entity_id__subscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntitySubscribeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySubscribeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_entity_api_v1_entities__entity_id__subscribe_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverviewResponse"];
                };
            };
        };
    };
    sources_api_v1_admin_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSourcesResponse"];
                };
            };
        };
    };
    processing_api_v1_admin_processing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProcessingResponse"];
                };
            };
        };
    };
    search_stats_api_v1_admin_search_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSearchStatsResponse"];
                };
            };
        };
    };
    generation_stats_api_v1_admin_generation_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGenerationStatsResponse"];
                };
            };
        };
    };
}
